import { Ship } from "../types";

const MOCK_SHIPS: Ship[] = [
  {
    __typename: "Ship",
    id: "GOMSTREE",
    active: true,
    home_port: "Port Canaveral",
    name: "GO Ms Tree",
    type: "High Speed Craft",
    image: "https://i.imgur.com/MtEgYbY.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:3439091/vessel:MR%20STEVEN",
    year_built: 2015,
  },
  {
    __typename: "Ship",
    id: "GOPURSUIT",
    active: false,
    home_port: "Port Canaveral",
    name: "GO Pursuit",
    type: "Cargo",
    image: "https://i.imgur.com/5w1ZWre.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:439594/vessel:GO%20PURSUIT",
    year_built: 2007,
  },
  {
    __typename: "Ship",
    id: "AMERICANCHAMPION",
    active: false,
    home_port: "Port of Los Angeles",
    name: "American Champion",
    type: "Tug",
    image: "https://i.imgur.com/woCxpkj.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:434663/vessel:AMERICAN%20CHAMPION",
    year_built: 1976,
  },
  {
    __typename: "Ship",
    id: "GOQUEST",
    active: true,
    home_port: "Port Canaveral",
    name: "GO Quest",
    type: "Cargo",
    image: "https://i.imgur.com/ABXtHKa.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:450521/vessel:GO%20QUEST",
    year_built: 2014,
  },
  {
    __typename: "Ship",
    id: "GONAVIGATOR",
    active: true,
    home_port: "Port Canaveral",
    name: "GO Navigator",
    type: "Cargo",
    image: "https://i.imgur.com/MjNWzhO.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:452540/vessel:GO%20NAVIGATOR",
    year_built: 2009,
  },
  {
    __typename: "Ship",
    id: "JRTI-2",
    active: true,
    home_port: "Port of Los Angeles",
    name: "Just Read The Instructions 2",
    type: "Barge",
    image: "https://i.imgur.com/7VMC0Gn.jpg",
    url: "",
    year_built: 2015,
  },
  {
    __typename: "Ship",
    id: "NRCQUEST",
    active: true,
    home_port: "Port of Los Angeles",
    name: "NRC Quest",
    type: "Cargo",
    image: "https://i.imgur.com/GvtuYUN.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:447294/vessel:NRC%20QUEST",
    year_built: 2002,
  },
  {
    __typename: "Ship",
    id: "OCISLY",
    active: true,
    home_port: "Port Canaveral",
    name: "Of Course I Still Love You",
    type: "Barge",
    image: "https://i.imgur.com/28dCx6G.jpg",
    url: "",
    year_built: 2015,
  },
  {
    __typename: "Ship",
    id: "PACIFICWARRIOR",
    active: false,
    home_port: "Port of Los Angeles",
    name: "Pacific Warrior",
    type: "Tug",
    image: "https://i.imgur.com/qdNDmYs.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:434121/vessel:PACIFIC%20WARRIOR",
    year_built: 1974,
  },
  {
    __typename: "Ship",
    id: "PACIFICFREEDOM",
    active: true,
    home_port: "Port of Los Angeles",
    name: "Pacific Freeedom",
    type: "Tug",
    image: "https://i.imgur.com/eJWx70Z.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:4249791/vessel:PACIFIC%20FREEDOM",
    year_built: 1976,
  },
  {
    __typename: "Ship",
    id: "BETTYRGAMBARELLA",
    active: false,
    home_port: "Port of Los Angeles",
    name: "Betty R Gambarella",
    type: "Tug",
    image: "https://i.imgur.com/ngYgFnn.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:428415/vessel:BETTY%20R%20GAMBARELLA",
    year_built: 1974,
  },
  {
    __typename: "Ship",
    id: "AMERICANISLANDER",
    active: false,
    home_port: "Port of Los Angeles",
    name: "American Islander",
    type: "Cargo",
    image: "https://i.imgur.com/jmj8Sh2.jpg",
    url: "https://www.marinetraffic.com/en/ais/details/ships/shipid:435112/vessel:AMERICAN%20ISLANDER",
    year_built: 1900,
  },
];

export { MOCK_SHIPS };
